export declare const GoogleParams: {
    contentDetails: string;
    snippet: string;
    statistics: string;
    ifParamIdIsBlank: string;
    id: string;
    fileDetails: string;
    player: string;
    processingDetails: string;
    recordingDetails: string;
    status: string;
    suggestions: string;
    topicDetails: string;
    auditDetails: string;
    brandingSettings: string;
    contentOwnerDetails: string;
    localizations: string;
    subscriberSnippet: string;
    limit: (postLimit: number) => number;
    paramIdentifier: {
        channels: string;
        search: string;
        videos: string;
        activities: string;
        captions: string;
        channelSections: string;
        i18nLanguages: string;
        i18nRegions: string;
        playlists: string;
        playlistItems: string;
        subscriptions: string;
    };
};
